// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegraDeCasamento.Infrastructure.Persistencia;

#nullable disable

namespace RegraDeCasamento.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(RegraDeCasamentoDbContext))]
    partial class RegraDeCasamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Familias", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apelido")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId", "Apelido")
                        .IsUnique();

                    b.ToTable("Membros", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.PedidoDeEntrada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ContaDoSolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeDoSolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RespondidoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContaDoSolicitanteId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("PedidosDeEntrada", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("DividaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DonoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumeroDaParcela")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PagaEm")
                        .HasColumnType("date");

                    b.Property<Guid?>("PagaPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DividaId");

                    b.HasIndex("FamiliaId", "PagaEm");

                    b.HasIndex("FamiliaId", "Vencimento");

                    b.ToTable("Despesas", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Divida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DonoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroDeParcelas")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PrimeiroVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Dividas", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Renda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataDeFim")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DiaDeRecebimento")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DonoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmDiaUtil")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UsoRestrito")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Rendas", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Mercado.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompradoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ParaQuemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId", "Dia");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("RegraDeCasamento.Infrastructure.Acesso.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TipoDeLogin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembroId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RegraDeCasamento.Infrastructure.Acesso.Conta", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RegraDeCasamento.Infrastructure.Acesso.Conta", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RegraDeCasamento.Infrastructure.Acesso.Conta", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.Membro", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.PedidoDeEntrada", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany("PedidosDeEntrada")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Despesa", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Financas.Divida", null)
                        .WithMany()
                        .HasForeignKey("DividaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Divida", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Financas.Renda", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Mercado.Compra", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Familia", null)
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RegraDeCasamento.Domain.Mercado.ItemDaCompra", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CompraId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<decimal>("Quantidade")
                                .HasPrecision(12, 3)
                                .HasColumnType("numeric(12,3)");

                            b1.Property<decimal>("ValorUnitario")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("CompraId");

                            b1.ToTable("ItensDaCompra", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompraId");
                        });

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("RegraDeCasamento.Infrastructure.Acesso.Conta", b =>
                {
                    b.HasOne("RegraDeCasamento.Domain.Familias.Membro", null)
                        .WithOne()
                        .HasForeignKey("RegraDeCasamento.Infrastructure.Acesso.Conta", "MembroId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegraDeCasamento.Domain.Familias.Familia", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("PedidosDeEntrada");
                });
#pragma warning restore 612, 618
        }
    }
}
